### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arve0** [flesler/node-spider#1]
What pattern would you use to prevent RangeError?

Currently, I add links to queue by calling `done` inside `done`:

```
    spider = new Spider({
      concurrent: 10, logs: true,
      headers: {
        'user-agent': 'codeclub_lesson_builder'
      },
      error: function(url, err){
        console.log('got err ', url, err);
      },
      done: function() {
        console.log('done');
        browserSync.exit();
        cb();
      }
    });
    var resources = {};
    var done = function(doc){
      if (doc.url.search('http://localhost:3000/') === 0) {
        // we are on localhost
        doc.$('a').each(function(){
          var href = this.attr('href');
          var url = doc.resolve(href);
          if (url in resources) {
            // already added
            return;
          }
          console.log('Found', url, doc.url);
          spider.queue(url, done);
          resources[url] = true;
        });
      }
    };
    var start = 'http://localhost:3000/index.html';
    spider.queue(start, done);
    resources[start] = true;
```

**Comment by arve0** [comment]
I guess maybe use this.done?

https://github.com/flesler/node-spider/blob/master/index.js#L63

**Comment by flesler** [comment]
You get that error on the `error` handler? or it throws?
It could be related to Node's HTTP module global agent maxConnections (by default at 5).
I could change that number based on `concurrent`. Does it also throw if concurrent is 5?

**Comment by arve0** [comment]
Debugged it here: https://github.com/flesler/node-spider/blob/master/index.js#L53

It's a problem when following links to binary files (in this case, a .zip). I'll do a simple check for text in `content-type` from the header.

**Comment by flesler** [comment]
Yes, seems like it happens when it jQueryfies the binary document, it kinda makes sense.
